# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-05-05 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('upwd', models.CharField(max_length=40)),
                ('uemail', models.CharField(max_length=40)),
                ('isDelete', models.BooleanField(default=False)),
                ('ucustomer', models.CharField(default='null', max_length=10)),
                ('uaddr', models.CharField(default='null', max_length=100)),
                ('uzipcode', models.CharField(default='null', max_length=6)),
                ('uphone', models.CharField(default='null', max_length=11)),
            ],
        ),
    ]
